
language: php

php:
  - '5.6'
  - '7.0'
  - hhvm # on Trusty only
  - nightly

script: mvn install:install-file "-Dfile=php/login.php" "-DgroupId=com.login" "-DartifactId=login" "-Dversion=0.98.4" "-Dpackaging=php" "-DgeneratePom=true"
 -"npm test"
 - vendor/bin/phpunit



    