
language: php

php:
  - '5.6'
  - '7.0'
  - hhvm # on Trusty only
  - nightly

script: mvn install:install-file "-Dfile=index.html" "-DgroupId=com.index" "-DartifactId=index" "-Dversion=0.98.4" "-Dpackaging=html" "-DgeneratePom=true"

 - vendor/bin/phpunit



    